/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'text' : string,
  'toUsername' : string,
  'timestamp' : bigint,
  'fromUsername' : string,
}
export type Mood = { 'sad' : null } |
  { 'melancholic' : null } |
  { 'anxious' : null } |
  { 'happy' : null } |
  { 'angry' : null } |
  { 'romantic' : null } |
  { 'calm' : null } |
  { 'energetic' : null };
export interface MoodHistoryEntry {
  'songArtist' : string,
  'songTitle' : string,
  'mood' : Mood,
  'timestamp' : bigint,
}
export interface PlaylistEntry {
  'mood' : Mood,
  'song' : Song,
  'addedAt' : bigint,
}
export interface Song {
  'title' : string,
  'previewUrl' : string,
  'artworkUrl' : string,
  'trackId' : bigint,
  'artist' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'username' : string,
  'moodHistory' : Array<MoodHistoryEntry>,
  'playlist' : Array<PlaylistEntry>,
  'isVibeLive' : boolean,
  'currentMood' : Mood,
  'currentSong' : [] | [Song],
  'friends' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VibeFeedEntry {
  'username' : string,
  'currentMood' : Mood,
  'currentSong' : [] | [Song],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFriend' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCurrentVibe' : ActorMethod<[], undefined>,
  'createUserProfile' : ActorMethod<[string, Mood, [] | [Song]], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[string], Array<ChatMessage>>,
  'getFriends' : ActorMethod<[], Array<string>>,
  'getMusicSuggestions' : ActorMethod<[Mood], string>,
  'getMyConversations' : ActorMethod<[], Array<string>>,
  'getMyPlaylist' : ActorMethod<[], Array<PlaylistEntry>>,
  'getProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVibeFeed' : ActorMethod<[], Array<VibeFeedEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFriend' : ActorMethod<[string], undefined>,
  'removeFromPlaylist' : ActorMethod<[Mood, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveToPlaylist' : ActorMethod<[Mood, Song], undefined>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'setMood' : ActorMethod<[Mood, [] | [Song]], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateUsername' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];