/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Mood = IDL.Variant({
  'sad' : IDL.Null,
  'melancholic' : IDL.Null,
  'anxious' : IDL.Null,
  'happy' : IDL.Null,
  'angry' : IDL.Null,
  'romantic' : IDL.Null,
  'calm' : IDL.Null,
  'energetic' : IDL.Null,
});
export const Song = IDL.Record({
  'title' : IDL.Text,
  'previewUrl' : IDL.Text,
  'artworkUrl' : IDL.Text,
  'trackId' : IDL.Nat,
  'artist' : IDL.Text,
});
export const MoodHistoryEntry = IDL.Record({
  'songArtist' : IDL.Text,
  'songTitle' : IDL.Text,
  'mood' : Mood,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'moodHistory' : IDL.Vec(MoodHistoryEntry),
  'currentMood' : Mood,
  'currentSong' : IDL.Opt(Song),
});
export const VibeFeedEntry = IDL.Record({
  'username' : IDL.Text,
  'currentMood' : Mood,
  'currentSong' : IDL.Opt(Song),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUserProfile' : IDL.Func([IDL.Text, Mood, IDL.Opt(Song)], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMusicSuggestions' : IDL.Func([Mood], [IDL.Text], []),
  'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVibeFeed' : IDL.Func([], [IDL.Vec(VibeFeedEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMood' : IDL.Func([Mood, IDL.Opt(Song)], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateUsername' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Mood = IDL.Variant({
    'sad' : IDL.Null,
    'melancholic' : IDL.Null,
    'anxious' : IDL.Null,
    'happy' : IDL.Null,
    'angry' : IDL.Null,
    'romantic' : IDL.Null,
    'calm' : IDL.Null,
    'energetic' : IDL.Null,
  });
  const Song = IDL.Record({
    'title' : IDL.Text,
    'previewUrl' : IDL.Text,
    'artworkUrl' : IDL.Text,
    'trackId' : IDL.Nat,
    'artist' : IDL.Text,
  });
  const MoodHistoryEntry = IDL.Record({
    'songArtist' : IDL.Text,
    'songTitle' : IDL.Text,
    'mood' : Mood,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'moodHistory' : IDL.Vec(MoodHistoryEntry),
    'currentMood' : Mood,
    'currentSong' : IDL.Opt(Song),
  });
  const VibeFeedEntry = IDL.Record({
    'username' : IDL.Text,
    'currentMood' : Mood,
    'currentSong' : IDL.Opt(Song),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUserProfile' : IDL.Func([IDL.Text, Mood, IDL.Opt(Song)], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMusicSuggestions' : IDL.Func([Mood], [IDL.Text], []),
    'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVibeFeed' : IDL.Func([], [IDL.Vec(VibeFeedEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMood' : IDL.Func([Mood, IDL.Opt(Song)], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateUsername' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };